Repository Enterprise-CMCS/macpro-mdct-carts, pull requests merged in 2024-05, with the labels that each got.

#139618 Bump action versions
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy.yml
  .github/workflows/pull-request.yml
Labels: ready for review

#139620 Upgrade CARTS to Node 20
  .nvmrc
  package.json
  services/app-api/serverless.yml
  services/carts-bigmac-streams/package.json
  services/carts-bigmac-streams/serverless.yml
  services/carts-bigmac-streams/yarn.lock
  services/database/package.json
  services/database/serverless.yml
  services/database/yarn.lock
  services/ui-auth/serverless.yml
  services/ui-src/serverless.yml
  services/ui/serverless.yml
  services/uploads/package.json
  services/uploads/serverless.yml
  services/uploads/yarn.lock
  yarn.lock
Labels: ready for review

#139621 Set up Serverless Compose
  .env_example
  deploy.sh
  package.json
  serverless-compose.yml
  services/app-api/package.json
  services/app-api/serverless.yml
  services/app-api/yarn.lock
  services/carts-bigmac-streams/handlers/configureConnectors.js
  services/carts-bigmac-streams/package.json
  services/carts-bigmac-streams/serverless.yml
  services/carts-bigmac-streams/yarn.lock
  services/database/serverless.yml
  services/ui-auth/serverless.yml
  services/ui-src/.env_example
  services/ui-src/serverless.yml
  services/uploads/serverless.yml
  yarn.lock
Labels: ready for review

#139626 Encode file name before allowing download on upload component
  services/ui-src/src/components/layout/UploadComponent.js
Labels: draft

#139625 Reduce possibile e2e failure by swapping "Indicate the range for premiums" to "Indicate the range"
  services/ui-src/src/components/fields/Checkbox.jsx
  services/ui-src/src/components/fields/Question.jsx
  tests/cypress/tests/integration/section1Fill.spec.js
Labels: waiting

#139639 Remove unmarshall options from Kafka calls
  services/carts-bigmac-streams/libs/kafka-source-lib.js
  services/carts-bigmac-streams/serverless.yml
  services/database/scripts/sync-kafka-2024.js
Labels: ready for review

#139642 Set Report Type to Combo to ensure theres a section 1 to fill in sect…
  tests/cypress/tests/integration/section1Fill.spec.js
Labels: ready for review

#139643 Remove possible E in label
  tests/cypress/tests/integration/section1Fill.spec.js
Labels: ready for review

#139637 Dev -> Val
  .env.tpl
  .env_example
  README.md
  run
  services/carts-bigmac-streams/libs/kafka-source-lib.js
  services/carts-bigmac-streams/serverless.yml
  services/database/scripts/sync-kafka-2024.js
  services/ui-auth/serverless.yml
  services/ui-src/.env.tpl
  services/ui-src/.env_example
  services/ui-src/env.sh
  services/ui-src/src/components/fields/Checkbox.jsx
  services/ui-src/src/components/fields/Question.jsx
  services/ui-src/src/styles/_header.scss
  services/ui/serverless.yml
  src/run.ts
  tests/cypress/README.md
  tests/cypress/cypress.config.js
  tests/cypress/package.json
  tests/cypress/tests/integration/section1Fill.spec.js
  tests/cypress/yarn.lock
Labels: ready for review
